{{- if .Values.configMap.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-frontend
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
immutable: false
data:
  {{- toYaml .Values.configMap.env | nindent 2 }}
{{- end }}
