{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
  {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "frontend.fullname" . }}-secret
  dataFrom:
  {{- toYaml .Values.externalSecret.dataFrom | nindent 4 }}
{{- end }}
