{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name | default (printf "%s-secret" (include "frontend.fullname" $)) }}
  labels:
  {{- include "frontend.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
  {{- toYaml .secretStoreRef | nindent 4 }}
  target:
    name: {{ .name | default (printf "%s-secret" (include "frontend.fullname" $)) }}
    {{- with .target }}
    {{- with .template }}
    template:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- if .dataFrom }}
  dataFrom:
  {{- toYaml .dataFrom | nindent 2 }}
  {{- end }}
  {{- if .data }}
  data:
  {{- toYaml .data | nindent 2 }}
  {{- end }}
{{- end }}
