{{- if .Values.secretStore.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name | default "openbao" }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.server }}
      path: {{ .Values.secretStore.path | default "secret" }}
      version: {{ .Values.secretStore.version | default "v2" }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.auth.mountPath | default "kubernetes" }}
          role: {{ .Values.secretStore.auth.role }}
          serviceAccountRef:
            name: external-secrets
{{- end }}
