{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}-backend-0
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    cert-manager.io/issue-temporary-certificate: "true"
    cert-manager.io/private-key-rotation-policy: Always
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hosts | join "," }}
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "backend.fullname" $ }}-backend
                port:
                  number: {{ $.Values.service.port }}
            path: /api/(.+)
            pathType: Prefix
    {{- end }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ include "backend.fullname" . }}-backend-0-tls
{{- end }}
