{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "backend.fullname" . }}-secret
  labels:
  {{- include "backend.labels" . | nindent 4 }}
data:
  PGDATABASE: {{ required "db.name is required" .Values.db.name | b64enc | quote }}
  DB_NAME: {{ required "db.name is required" .Values.db.name | b64enc | quote }}
  PGHOST: {{ required "db.host is required" .Values.db.host | b64enc | quote }}
  DB_HOSTNAME: {{ required "db.host is required" .Values.db.host | b64enc | quote }}
  PGHOSTADDR: {{ required "db.host is required" .Values.db.host | b64enc | quote }}
  PGUSER: {{ required "db.user is required" .Values.db.user | b64enc | quote }}
  DB_USER: {{ required "db.user is required" .Values.db.user | b64enc | quote }}
  PGPORT: {{ required "db.port is required" .Values.db.port | b64enc | quote }}
  DB_PORT: {{ required "db.port is required" .Values.db.port | b64enc | quote }}
  PGPASSWORD: {{ required "db.password is required" .Values.db.password | b64enc | quote }}
  DB_PASSWORD: {{ required "db.password is required" .Values.db.password | b64enc | quote }}
  db_password: {{ required "db.password is required" .Values.db.password | b64enc
    | quote }}
  db_port: {{ required "db.port is required" .Values.db.port | b64enc | quote
    }}
  db_user: {{ required "db.user is required" .Values.db.user | b64enc | quote
    }}
type: Opaque
{{- end }}
